"seed": 12345
"population_id": 0
"replicates": 3

"species": "HomSap"
"demo_models": [
    {"id":"Constant", 
    "num_samples_per_population": [100],
    },
    {"id":"OutOfAfrica_3G09",
    "num_samples_per_population": [100,100,100],
    }
    {"id":"OutOfAfricaArchaicAdmixture_5R19",
    "num_samples_per_population": [100,100,100],
    }
]
"genetic_map": "HapMapII_GRCh37"
"chrm_list": "chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21"
"dfe_list": ["Gamma_H17"]
"annotation_list": ["all_sites", "ensembl_havana_104_exons"]
"output_dir": "results"


# slim settings
"slim_scaling_factor": 1
"slim_burn_in": 10

# n(t) specific configs
"num_sampled_genomes_msmc" : [2, 8]
"num_sampled_genomes_per_replicate": [2, 8]
"num_msmc_iterations" : 1

# exe paths
"poly_dfe_exec": "ext/polyDFE/polyDFE-2.0-linux-64-bit"
"dfe_alpha_data_path_1": "ext/DFE-alpha/data"
"dfe_alpha_data_path_2": "three-epoch" 
"msmc_exec" : "ext/msmc2/build/release/msmc2"
"stairwayplot_code" : "stairwayplot/swarmops.jar"
